### ISSUE TITLE
Error No JSON object could be decoded running query

### ISSUE THREAD

**Issue by jonarrien** [cezarsa/sublime-sparql-runner#1]
Hi, I'm trying to run a query against a Virtuoso endpoint and the plugin seems not be able to decode the JSON.

The endpoint:                  http://semantic.eea.europa.eu/sparql

The Query => 

PREFIX a: http://www.eea.europa.eu/portal_types/Data#
PREFIX dcterms: http://purl.org/dc/terms/

SELECT DISTINCT ?subj ?issued ?title  ?description WHERE {
  ?subj a a:Data ;
        dcterms:title ?title ;
        dcterms:description ?description;
        dcterms:issued ?issued.
} ORDER BY ?effective

**Comment by leerssej** [comment]
Similar issue:
Running a query against wikibase and wikidata endpoints and get the "Error no JSON object could be decoded running query."

PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?h ?hospital ?hl ?hospitall WHERE {
   ?h wdt:P31 wd:Q16917 .
   ?h wdt:P646 ?hospital .
  OPTIONAL  {  
     ?h rdfs:label ?hl filter (lang(?hl) = "en") .
  } 
  OPTIONAL { 
     ?hospital rdfs:label ?hospitall filter (lang(?hospitall) = "en"). 
   }
 }

What should I change?
(Note: Query tested and functioning here: https://query.wikidata.org/)
